import Head from 'next/head';

import { AppLayaout } from '../components/AppLayaout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" yarn />
      </Head>
      <AppLayaout></AppLayaout>

      <style jsx>{`
        h1 {
          color: red;
          font-size: 1.5em;
        }
      `}</style>
    </>
  );
}
